[profile.default]
  solc = "0.8.30"
  src = "src"
  out = "out"
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 200
  viaIR = true

remappings = [ 
  "@solady/src=lib/solady/src",
  "@solady/test=lib/solady/test",
  '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
  '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
  '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
  '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  'solidity-bytes-utils/contracts/=lib/solidity-bytes-utils/contracts',
]

[fuzz]
  runs = 256
  max_assume_rejects = 1000

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[doc]
  ignore = ["**/*.t.sol"]
  out = "docs"
  repository = "https://github.com/0xHustleLabs/wnape-apechain"

[rpc_endpoints]
  apechain = "${APECHAIN_RPC_URL}"

[etherscan]
  apechain = { key = "${APESCAN_API_KEY}", url = "https://api.apescan.io/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
